general {
    disable_loading_bar = true
    grace = 300
    hide_cursor = true
    no_fade_in = false
}

background {
    monitor =
    path = screenshot
    blur_passes = 4           
    blur_size = 7
    noise = 0.02
    contrast = 0.9
    brightness = 0.85
    vibrancy = 0.2
    vibrancy_darkness = 0.1
    color = rgba(89b4faff)    
}

image {
    path = /home/azure/Downloads/gura.png    
    size = 490                          
    rounding = 0                       
    border_size = 0
    #border_color = rgba(89b4faff)    
    position = -580, -210
    halign = center
    valign = center
}

input-field {
    size = 300, 60
    outline_thickness = 3
    dots_size = 0.3
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(89b4fa88)        
    inner_color = rgba(1e1e2e88)        
    font_color = rgb(89b4fa)            
    fade_on_empty = true
    font_family = JetBrainsMono Nerd Font Mono
    placeholder_text = <i>enter pass 🦈</i>
    hide_input = false
    position = 0, -80
    halign = center
    valign = center
}

label {
    text = cmd[update:1000] echo "<span font='120'>$(date +"%H:%M")</span>"
    color = rgba(89b4faee)              
    font_size = 120
    font_family = JetBrainsMono Nerd Font
    position = 0, 220
    halign = center
    valign = center
}

label {
    text = $USER  
    color = rgba(bbbbbbaa)
    font_size = 28
    font_family = sans-serif
    position = 0, -180
    halign = center
    valign = center
}

label {
    text = "do not worry she won't bite"
    color = rgba(89b4faaa)
    font_size = 20
    position = 0, -250
    halign = center
    valign = center
}
